--185
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p>DriveTime is setting new standards for the subprime used car dealer industry. Buying a used car with credit issues can be very difficult and actually put you in a worse position than you were in before. Drivetime has been changing the auto finance industry since 2002 -- beginning with the customer experience. At DriveTime we care about our customers and work to simplify the car buying process. You can get approved for a bad credit or no credit auto loan in under 2 minutes and see your down payment options on a selection of vehicles before you step foot in a DriveTime Dealership. Find financing for all credit types and get approved for an auto loan at DriveTime knowing your buying power.</p><h2>Used Cars, Trucks & SUV&#39;s</h2><p>Shopping for used cars at most dealerships can be discouraging. Other dealerships may have a small selection of vehicles, pushy sales tactics, or nickel and dime you on price. Buying a used car at DriveTime is different. We stock over 5000 used cars, trucks and SUVs providing you the freedom of choice in your search for a used vehicle. We also have a no-haggle policy, so the price listed is the price you pay for the vehicle. We have 140+ Bad Credit Car Dealerships to choose from across the country. Let DriveTime help you get into your next used car!</p><p>Check out our full featured mobile website now to view our wide vehicle selection nationwide or to find a dealership near you today!</p>', 
 WHERE dynamickey = 'seo-section' AND dynamicForm = 'home-seo' AND dynamicItem = 'content'; 
--256
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Get approved for financing for this  used vehicle.  ', 
 WHERE dynamickey = 'seo-section' AND dynamicForm = 'mob-ga1-vehicle' AND dynamicItem = 'seo_h2'; 
--176
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p>DriveTime brings to you this %YEAR% %MAKE% %MODEL% with %MILEAGE% miles, located in %REGION%, %ST%. Your search for a used %VEHICLETYPE% in %REGION% ends here at DriveTime. We carry used %YEAR% %MAKE% %MODEL%s in stock for you to test drive and take home today! Not only do we have %MAKE% %MODEL%s in stock, but shop at our %REGION% used %VEHICLETYPE% dealership featuring a wide selection of used cars to choose from. </p> <p>Different than your typical buy here pay here dealership, DriveTime offers this %YEAR% %MAKE% %MODEL% for sale with a multi-point inspection* along with several ownership benefit programs to help you throughout your experience with this %MAKE% %MODEL%.</p> <p>With over %DEALERCOUNT% used car dealerships in %STATECOUNT% states, if this %YEAR% %MAKE% %MODEL% is not the exact vehicle that you desire, check out other used %VEHICLETYPE%s in %REGION% for sale at our DriveTime location.</p><p><br>*DriveTime is not able to complete recall repairs, so vehicles may be subject to open recalls.ÿ You can check whether any vehicle is subject to an unrepaired recall at <a href="http://www.safercar.gov/" target="_blank">www.safercar.gov</a>.</p>', 
 WHERE dynamickey = 'seo-section' AND dynamicForm = 'vehicle-detail' AND dynamicItem = 'content'; 
--850
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p>DriveTime is the leading used car dealer helping people find and finance the perfect vehicle regardless of their credit. Unlike traditional buy here pay here dealerships, at DriveTime, we aim to put you in a used car with flexible, affordable financing packages through our in-house financing programs. When you apply for car financing with DriveTime, our team of sales advisors in %REGION% will work to provide you with your personalized financing options based on your specific credit situation. As the largest dealership helping people find and finance their next used car, we personalize your auto loan into a package that works for your specific credit situation. </p> <p>We have a vast selection of used cars for sale in %REGION%, each of which has gone through a multi-point inspection*. The other buy here pay here dealerships in %REGION% may not care about their vehicle selection and dealership experience like we do.  Each car comes with an AutoCheck vehicle history report and is covered by a 30 day / 1500 mile limited warranty. With a wide selection of vehicles at each dealership nationwide, we are confident that you will find your perfect vehicle on one of our lots. </p> <p>At DriveTime, we are committed to taking the hassle out of buying a used car. Avoid the hassle of dealing with unreliable buy here pay dealership in %REGION% and drop into your nearest DriveTime store where you can browse the available used cars and speak to an advisor about your financing options. Schedule an appointment at DriveTime dealership in %REGION% near you to find and finance your vehicle today! <br>*DriveTime is not able to complete recall repairs, so vehicles may be subject to open recalls.ÿ You can check whether any vehicle is subject to an unrepaired recall at <a href="http://www.safercar.gov/" target="_blank">www.safercar.gov</a></p>', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'buy-here-pay-here' AND dynamicItem = 'content'; 
--856
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'If you are looking to buy a used car in %REGION%, don&#39;t settle for a dealer with a poor selection of cars. At DriveTime, we have %ALLVEHICLECOUNT% used vehicles across %ALLDEALERCOUNT% dealerships nationwide and believe you can find your ideal vehicle in our inventory. We also offer upfront financing options to help you buy your desired car. You can get approved online and shop used cars knowing your options. At DriveTime, every used car goes through a multi-point inspection* before it ever arrives on the lot. We also provide a vehicle history report for each vehicle and they are covered by a 30 day / 1500 mile limited warranty.  We sell about 80,000 used cars annually and are confident that you too can find your ideal vehicle in your nearest %REGION% lot. As the leading subprime dealer and finance company, we also offer financing for all of our used vehicles. When you apply for a loan with DriveTime, our sales advisors in %REGION% work to create a financing package for you. Our goal is to provide you with financing terms that are personalized to your credit situation, so that you can purchase a car that you want and need. Drop into one of our %REGION% DriveTime dealerships and shop for your next used car with us. With dozens of vehicles available to view and test drive, we are confident you will find one that you will love, without the haggling and high-pressure environment of traditional dealerships. You can also browse through our inventory on our website for used cars near you. When you find a car you like, you can schedule your visit online or call us at 1-888-418-1212. <br>*DriveTime is not able to complete recall repairs, so vehicles may be subject to open recalls.ÿ You can check whether any vehicle is subject to an unrepaired recall at <a href="http://www.safercar.gov/" target="_blank">www.safercar.gov</a></p>', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'used-car' AND dynamicItem = 'content'; 
--860
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Buying a used car is easy at DriveTime thanks to our car financing options. As the leading dealership helping people find and finance vehicles regardless of their credit, we have approved more than two million people for financing -even with bad credit. When you apply for car financing with DriveTime, we work with you to not only find the perfect vehicle for you, but also to create an affordable financing package regardless of your credit. We have worked with people of all credit types to provide personalized financing options and upfront pricing. Unlike at other dealerships, we offer a no-pressure, no-haggling environment where our goal is to provide you with an affordable financing package so you can purchase your perfect vehicle. Visit your nearest %REGION% dealership and experience the DriveTime difference. When you visit one of our %REGION% stores, you will find a wide selection vehicles. All our used cars are put through a multi-point inspection* before they arrive at the lots and each one is covered by a 30 day / 1500 mile limited warranty.  You also have an option to purchase up to a 5 Year / 50,000 Mile Vehicle Protection Plan. We also provide an AutoCheck vehicle history report for each of our cars. Once you find your perfect vehicle, our sales advisors work with you to create a financing package that works for you, whether or not you have bad credit. Visit your nearest %REGION% DriveTime dealership and speak to an advisor about your car financing options regardless of your credit. We are committed to helping people overcome past financial hardships by providing bad credit car financing. With up to 100 cars at each of our dealerships, we are sure you will find your next used vehicle, and we will work with you to provide the financing you need to buy it. You can also browse our inventory online, and can begin your application in just two minutes. For more information call us toll free at 1-888-418-1212. <br>*DriveTime is not able to complete recall repairs, so vehicles may be subject to open recalls.ÿ You can check whether any vehicle is subject to an unrepaired recall at <a href="http://www.safercar.gov/" target="_blank">www.safercar.gov</a></p>', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'bad-credit-car-financing' AND dynamicItem = 'content'; 
--865
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Are you looking for a cheap car in %REGION%? Skip the unreliable dealerships that stock old, high mileage and visit your nearest DriveTime dealership. At DriveTime, we have more than %ALLVEHICLECOUNT% used vehicles for sale across the country. Our inventory consists of a wide selection of cars, trucks, SUVs and vans to help you find your next used vehicle. So what makes DriveTime cars different? We understand the risks involved with purchasing a cheap car, and advise you to be weary in your search. At DriveTime every used car goes through a multi-point inspection* before it ever arrives on the lot. We provide a 30 day / 1500 mile limited warranty and an AutoCheck vehicle history report for all our vehicles. A cheap car isn&#39;t always the best option for your future in terms of quality and selection. DriveTime also helps consumers that are looking for used cars by providing them with financing options regardless of their credit. Since 2002, we have approved more than 2 million people for auto financing. We finance all our vehicles and work with people of all credit types to help the get into theirnext used vehicle. Ditch the cheap car lots with questionable selection and drop in to your nearest %REGION% DriveTime dealership and browse our available inventory. Our sales advisors are ready to help you find and finance a car regardless of your credit. Get approved online today and shop knowing your financing options! <br>*DriveTime is not able to complete recall repairs, so vehicles may be subject to open recalls.ÿ You can check whether any vehicle is subject to an unrepaired recall at <a href="http://www.safercar.gov/" target="_blank">www.safercar.gov</a></p>', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'cheap-car' AND dynamicItem = 'content'; 
--875
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p>The great part about doing business with DriveTime is that you have options when looking for %REGION% used auto sales. We offer simple online financing options, a wide selection of used autos in inventory, and friendly customer service, all for your convenience. Finding used auto sales in %REGION% has never been easier. Whether you are a first time buyer or experienced shopper, we would love to help guide you through the process. </p> <p> Sometimes it&#39;s hard to know whether you are really finding a good deal on used auto sales in %REGION%. With DriveTime Auto Sales, we remove that pressure by being up front with all of our customers. When searching %REGION% auto sales dealerships, make sure you consider total price, car value, cost of ownership, and interest rate when determining a good deal. At DriveTime, we are happy to help you find the best deal available to you. </p> <p> Are you looking to purchase a used car with damaged or compromised credit? Many %REGION% auto sales dealerships will either turn you away, or offer low-quality choices. At DriveTime auto sales, we do business differently. We offer a number of choices in our online inventory for those looking to purchase a car with bad or no credit. Searching for used auto sales in %REGION% doesn&#39;t have to be difficult. We would love to show you why. </p> <p> If you&#39;re like most car buyers, you can&#39;t stand the process of haggling for a good price. Well, if you&#39;re looking for used auto sales in %REGION%, that&#39;s usually how it goes. At DriveTime auto sales, we are changing the game. We offer %REGION% auto sales in a no-haggle, hassle-free environment. That means every car on our lot is priced and marked accurately ? without the need for further negotiation. </p>', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'used-auto-sales' AND dynamicItem = 'content'; 
--880
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Obtaining auto financing and buying a used car is easy when you visit your nearest %REGION% DriveTime dealership. As the leading %REGION% dealership helping people find and finance vehicles regardless of their credit, we have approved more than two million people of all credit types for auto financing. Since 2002, we have differentiated ourselves from other %REGION% dealerships by providing used cars and simple, personalized auto financing. In that time, we have approved more than two million people of all credit types for used auto financing. Our financial advisors in %REGION% are trained to work with all %REGION% customers to help them secure financing and give them options to get into the right used vehicle for their specific situation. We have more than %ALLDEALERCOUNT% DriveTime dealerships across the country, including %DEALERCOUNT% in %REGION%, and all have up to %VEHICLECOUNT% used cars for sale. Every DriveTime used car goes through a multi-point inspection* before it ever arrives on the lot and each one is covered by a 30 day / 1500 mile limited warranty.  We also provide an AutoCheck vehicle history report for each of our %REGION% cars so you can understand the history of any vehicle you&#39;re interested in. Don&#39;t let your past financial hardships prevent you from getting into a reliable used car. We have approved more than two million people of all credit types for auto financing, therefore we are confident that we can work with you to find and finance your next used vehicle. Stop by our nearest %REGION% location and speak to a sales advisor, or begin your auto financing application online in just two minutes. For more information call us toll free at 1-888-418-1212. <br>*DriveTime is not able to complete recall repairs, so vehicles may be subject to open recalls.ÿ You can check whether any vehicle is subject to an unrepaired recall at <a href="http://www.safercar.gov/" target="_blank">www.safercar.gov</a></p>', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'auto-financing' AND dynamicItem = 'content'; 
--885
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p> Finding the best deals on used cars can sometimes feel like a game. Many %REGION% used car sales dealerships like to make you haggle and fight for a good price. At DriveTime auto sales, we don&#39;t see the value in that. We prefer to offer upfront, honest prices in a haggle-free environment. For car sales in %REGION%, come see what we have to offer. </p> <p> While buying a car is usually an exciting time, it can be hard to find a reputable %REGION% car sales dealership with a great selection in your market. Car sales in %REGION% don&#39;t have to operate that way. At DriveTime, we offer a no-haggle environment. </p> <p> The quality of used cars fluctuates considerably between %REGION% car sales dealerships. That&#39;s why it&#39;s important that you educate yourself on what makes a used car dealership great. DriveTime should be your top destination for car sales in %REGION% with upfront pricing, AutoCheck History reports for every vehicle, and a dealership experience like no other. </p> <p> Buying from a %REGION% used car sales dealership has never been easier. DriveTime auto sales offers no-haggle pricing, personalized financing options, and friendly customer service. If you&#39;ve been searching for car sales in %REGION%, DriveTime is your answer. With incredible options and benefits, you&#39;ll wonder why you ever shopped for a car anywhere else. Find out what DriveTime has to offer! </p>', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'used-car-sales' AND dynamicItem = 'content'; 
--890
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p> Are you shopping for a used car but are worried about past credit problems? Don&#39;t let your bad credit history hold you back from purchasing a car. At DriveTime %REGION%, our goal is to get you into a used car that&#39;s right for you by providing flexible bad credit car loans. Stop by your nearest %REGION% DriveTime Dealership and find out how you can get yourself into a great used car regardless of your credit. </p> <p> At traditional dealerships in %REGION%, when you apply for a bad credit car loan, many dealers take your application and simply forward it to banks, who then evaluate your eligibility based on your financial past. At DriveTime %REGION%, we strive to find you the best car loan for your financial needs while giving you vehicle options for you to choose from. Our sales advisors in %REGION% assess your present situation and work with you to find you a loan that&#39;s personalized to you and your credit. </p> <p> As an integrated financing company and dealership, we have thousands of used cars for sale across our %ALLDEALERCOUNT% dealerships nationwide. Whether you are looking for a car, van, truck or SUV, we want to help you find a used vehicle near you. We will also work with you to obtain a loan in %REGION% regardless of your credit situation with our simple online approval process. We have %DEALERCOUNT% local dealerships in %REGION% with up to %VEHICLECOUNT% used cars, so we encourage you to visit your closest location and find your next vehicle. </p> <p> Obtaining a car loan with bad credit in %REGION% has never been easy, but at DriveTime, we specialize in helping people of all credit types buy their next used car. Our sales advisors are committed to working with our customers to help them find a vehicle that meets their needs, and to secure a loan to purchase.  Stop by your closest %REGION% dealership today, or begin your application online in just two minutes! For more information call us toll free at 1-888-418-1212. </p>', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'bad-credit-car-loans' AND dynamicItem = 'content'; 
--895
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p> Securing auto financing in %REGION% may seem impossible for those who have faced financial difficulties or have not built strong credit. DriveTime dealers are the answer for many consumers. Regardless of past credit problems, DriveTime focuses on today to help individuals secure simple, flexible auto financing while driving home in the used vehicle of their choice. Find out how we stand out amongst other %REGION% auto financing dealers. </p> <p> At DriveTime, we believe obtaining poor credit auto financing in %REGION% shouldn&#39;t mean settling for a low quality car. When customers come in to shop for their next used car, our friendly sales staff work with them to identify which vehicle they will most easily afford and enjoy. </p> <p> Does it seem like every %REGION% auto financing dealer has turned you down ? even those offering poor credit auto financing? At DriveTime, our commitment to financing drivers with bad credit amounts to more than words. We understand the many circumstances that lead to damaged credit and want to see you succeed in the future. That&#39;s why we work with you to find the ideal payment arrangements to keep you on track and behind the wheel. </p> <p> DriveTime  focuses on getting  %REGION% residents approved for the poor credit auto financing needed to get them into a car they need or want. Drive off a DriveTime lot today in your next used car. </p>', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'auto-finance' AND dynamicItem = 'content'; 
--905
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Getting an auto loan and buying a used car is easy when you visit your nearest %REGION% DriveTime dealership. As one of the nation&#39;s largest subprime dealership helping people find and finance vehicles regardless of their credit, we have approved more than two million people of all credit types for auto loans. Since 2002, we have differentiated ourselves from other dealerships by focusing on providing a wide selection used cars and a great, no-hassle car buying experience. In that time, we have approved more than two million people of all credit types for used auto loans. Our sales advisors in %REGION% are trained to work with all customers to help them secure loans to purchase their next used vehicle. We have %ALLDEALERCOUNT% DriveTime dealerships across the country, including %DEALERCOUNT% in %REGION% with up to %VEHICLECOUNT% used cars for sale. All our used cars are put through a multi-point inspection* before they make it to the lots and each one is covered by a 30 day / 1500 mile limited warranty.  We also provide an AutoCheck vehicle history report for each of our cars. If you are looking for a used car, visit your nearest %REGION% DriveTime dealership and test drive some of our vehicles and speak to an advisor about getting approved for an auto loan regardless of your credit. Start your auto loan application in two minutes online or call us toll free at 1-888-418-1212. <br>*DriveTime is not able to complete recall repairs, so vehicles may be subject to open recalls.ÿ You can check whether any vehicle is subject to an unrepaired recall at <a href="http://www.safercar.gov/" target="_blank">www.safercar.gov</a></p>', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'auto-loan' AND dynamicItem = 'content'; 
--910
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Obtaining a car loan and buying a used car is simple when you visit your nearest %REGION% DriveTime dealership. As one of the leading %REGION% dealership helping people find and finance vehicles regardless of their credit, we have approved more than two million people of all credit types for car loans. Since 2002, we have differentiated ourselves from other %REGION% dealerships by providing a wide selection of used cars and personalized financing options for any credit type. In that time, we have approved more than two million people of all credit types for used car loans. Our sales advisors in %REGION% are trained to work with all %REGION% customers to help them secure loans to purchase their next used vehicle with flexible financing options. We have %ALLDEALERCOUNT% DriveTime dealerships across the country, including %DEALERCOUNT% in %REGION% with up to %VEHICLECOUNT% used cars for sale. Every DriveTime used car goes through a multi-point inspection* before it ever arrives on the lot and each one is covered by a 30 day / 1500 mile limited warranty.  We also provide an AutoCheck vehicle history report for each of our %REGION% cars. Don&#39;t let your past financial hardships prevent you from getting into a used car. Stop by our nearest %REGION% location and speak to our friendly sales staff or fill out your auto loan application online in just two minutes. For more information you can call us toll free at 1-888-418-1212. <br>*DriveTime is not able to complete recall repairs, so vehicles may be subject to open recalls.ÿ You can check whether any vehicle is subject to an unrepaired recall at <a href="http://www.safercar.gov/" target="_blank">www.safercar.gov</a></p>', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'car-loans' AND dynamicItem = 'content'; 
--915
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'If you are looking for a used truck, consider visiting your local %REGION% DriveTime dealership. DriveTime is the nation&#39;s leading dealership helping people with bad credit find and finance a used vehicle. We carry a wide selection of used trucks and believe you can find your next used vehicle in our inventory. We also offer personalized financing options to help you buy a new-to-you truck you want. Since 2002, we have sold more than a million used cars and trucks. Every DriveTime Truck goes through a multi-point inspection* before it ever arrives on the lot. We also provide a vehicle history report for each vehicle and they are covered by a 30 day / 1500 mile limited warranty.  We sell more than 80,000 used vehicles annually and are confident that you too can find a selection of trucks in your nearest %REGION% lot. Not only do we provide used cars and trucks to buyers, we also offer financing for all of our used vehicles. Our sales advisors are trained to work with people of all credit types to help them secure a loan to buy their next vehicle. Drop into one of our %REGION% DriveTime dealerships and shop for your next truck with us. With dozens of vehicles available to view and test drive, we think you&#39;ll find a selection to fit your needs.  Browse through our inventory online for used trucks near you and schedule a visit to your local DriveTime dealership. You can also call us toll free at 1-888-418-1212. <br>*DriveTime is not able to complete recall repairs, so vehicles may be subject to open recalls.ÿ You can check whether any vehicle is subject to an unrepaired recall at <a href="http://www.safercar.gov/" target="_blank">www.safercar.gov</a></p>', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'used-truck' AND dynamicItem = 'content'; 
--920
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p> It can be difficult to find no credit car financing in %REGION%. When you do find a deal, you might find that a traditional dealership won&#39;t finance you with no credit history. But, that&#39;s not always the case. DriveTime auto sales offers no credit auto loans to first time buyers and others with compromised credit history. We believe everyone deserves a chance to own a vehicle and are proud to back up that belief with personalized no credit financing options. </p> <p> Shopping traditional car lots limits your options when looking for no credit car financing in %REGION%. That&#39;s because the large majority of car dealerships require third party financing to complete a lease or purchase. When choosing DriveTime, we give you the benefit of the doubt and offer no credit auto loans. This simplifies the process and enables you to get the car you need and want. </p> <p> For no credit car financing in %REGION%, you will want to check out what we have to offer at DriveTime. Whether you have a damaged credit history or no credit at all, we are happy to offer our customers no credit auto loans and other flexible financing options. That&#39;s right, you can get approved in two minutes or less with the opportunity to choose between a variety of styles and options. </p> <p> When looking for a used car, you should be focused on quality and price. But without good credit history, this often takes a backseat to merely qualifying. Take qualifying out of the picture with DriveTime Auto Sales. We offer no credit auto loans so that you can concentrate on what really matters: finding your next used car. For no credit car financing in %REGION%, let DriveTime be your one and only destination.', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'no-credit' AND dynamicItem = 'content'; 
--925
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p> Should I buy new or used? That&#39;s the popular question. In many cases, you&#39;ll find used is the smart way to go when shopping on a budget. When searching for used SUVs for sale in %REGION%, make sure you consider DriveTime auto sales. We offer a deep selection of %REGION% used SUVs and match each with flexible financing options, and friendly customer service. </p> <p> When looking at used SUVS for sale in %REGION%, you have a plethora of choices. One of the first decisions you will have to make is in regards to size. Do you want a crossover, full-size, or mid-sized SUV? Each comes with benefits and limitations, so it&#39;s important to spend some time researching. At DriveTime, we post all of our SUV inventory online so you can shop for your perfect fit before you step foot on the lot. </p> <p> Common SUV safety issues include larger than normal blind spots and lower fuel efficiency. In addition to these potential safety risks, there are a number of benefits. Consider that they are good for off-roading and traveling with large families. If you are interested in used SUVs for sale in %REGION%, make sure you understand the facts and choose wisely. </p> <p> At DriveTime, buying used SUVs in %REGION% has never been easier. We offer flexible financing options for those with bad credit or no credit at all. Our and knowledgeable staff is standing by ready to help you find the right SUV for your specific credit situation. If you are searching for %REGION% used SUVs, your search is over. Come by our DriveTime dealership and see what we&#39;re all about. </p>', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'used-suv' AND dynamicItem = 'content'; 
--935
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Are you looking to buy a car but are dreading traditional high-pressure environment of used car dealerships? Visit your nearest DriveTime dealership and experience the DriveTime difference. Unlike at other in-house financing dealerships, at DriveTime, we dont just help you find your next used car, we help you secure the financing needed to purchase the vehicle through our in-house financing program. As one of the leading in-house financing dealership helping people with bad credit, DriveTime strives to provide affordable financing for our used cars. Our sales advisors work with you to create personalized financing options while getting you into the vehicle that you want. We have approved more than 2 million customers since 2002 and can help you get approved and see your financing options in under two minutes. We have a vast selection of used cars for sale in %REGION%. Every DriveTime used car goes through a multi-point inspection* before it ever arrives on the lot. They also come with an AutoCheck vehicle history report as well as coverage by a 30 day / 1500 mile limited warranty. We complete about 80,000 used car sales or more each year and our inventory changes daily ? search our inventory online. Drop into one of our %REGION% DriveTime dealerships to speak to one of our sales advisors about our in-house financing programs. With dozens of vehicles available to view and test drive we will help you find one that you will love, without the haggling and high-pressure environment of traditional in-house financing dealerships. You can also browse through our inventory on our website for vehicles near you. Get approved for in-house financing online or at a DriveTime Dealership near you! <br>*DriveTime is not able to complete recall repairs, so vehicles may be subject to open recalls.ÿ You can check whether any vehicle is subject to an unrepaired recall at <a href="http://www.safercar.gov/" target="_blank">www.safercar.gov</a></p>', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'in-house-financing' AND dynamicItem = 'content'; 
--940
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p>For those of you with bad credit history, shopping for a car or truck is difficult. While you may find a vehicle that fits your budget, it can be difficult to convince a dealership of your financial responsibility. At %REGION% tote the note dealers, bad credit history doesn&#39;t matter. How does it work? %REGION% dealers with tote the note are able to offer in-house financing, as opposed to using third party lending institutions. </p> <p> If you&#39;ve had experience dealing with %REGION% dealers offering tote the note financing, you understand that these offers aren&#39;t everything they&#39;re cracked up to be. While they do allow customers with bad credit the chance to get into a vehicle, they can do so with low quality cars and trucks. If you have bad credit history but still want a used vehicle, don&#39;t go with %REGION% tote the note dealers; choose DriveTime! </p> <p> While %REGION% dealers with tote the note financing offer a wonderful opportunity to those with bad credit, it often comes at the expense of a high pressure bait-and-switch sales environment. At DriveTime, we are not associated with %REGION% tote the note dealers, which means we can offer flexible financing and payment options. We will work you to get you into the right vehicle for your specific situation ? without the stress of a traditional tote the note car buying experience. </p> <p> If you want upfront vehicle pricing and a no-haggle dealership experience, you may want to look past %REGION% dealers with tote the note financing. While %REGION% tote the note dealers may offer vehicles to those with bad credit history, it often comes with setbacks and surprises.  At DriveTime, we pride ourselves on our simple financing process and hassle-free sales experience, regardless of credit history. Apply online or schedule a test drive today! </p>', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'tote-the-note' AND dynamicItem = 'content'; 
--930
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Shopping for used vans in %REGION% doesnt have to be difficult. In fact, at DriveTime it can be rather simple. We offer financing for all types of credit and will give anyone and everyone a shot. Our simple van shopping experience makes dealing with other used vans for sale in %REGION% look like a hassle. If you want to simplify your shopping experience, let DriveTime take the hassle out of buying. If you are looking for used vans in %REGION%, it would benefit you greatly to shop a dealership that offers personalized financing options. That gives you the flexibility of finding a van you like and then making the decision. At DriveTime, our %REGION% used vans are available to anyone. Whether you have bad credit, no credit, we are happy to approve you for financing. Equally as important as choosing the type of van you want is choosing the features you want it to have. %REGION% used vans come in a variety of shapes and sizes, with a number of different bells and whistles. Before purchasing a used van, make sure you know which features you want. At DriveTime, we have vans with rear view camera displays, automatic sliding doors, built-in DVD players, and more. "Used vans for sale in %REGION%!" the sign reads. But what comes with the van? At DriveTime, you get more than a used vehicle. You get the DriveTime shopping experience, which includes friendly customer service, no-haggle pricing, a 30 day / 1500 mile limited warranty, and a 5-day return allowance. Buying used vans in %REGION% has never been easier. Come find out what the DriveTime experience feels like today.', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'used-van' AND dynamicItem = 'content'; 
--858
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Car Financing options for people with bad credit in %REGION%.  Take 2 minutes and apply  for %REGION% bad credit car financing.', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'bad-credit-car-financing' AND dynamicItem = 'metadescription'; 
--863
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Cheap doesnt have to be lower quality in  %REGION%! Search cheap %REGION% cars for sale with car financing options for all credit types. ', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'cheap-car' AND dynamicItem = 'metadescription'; 
--888
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Stop beating yourself up due to your bad credit! At DriveTime %REGION%, we understand. It&#39;s our business to get you into a used car that&#39;s right for you, regardless of your credit score.', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'bad-credit-car-loans' AND dynamicItem = 'metadescription'; 
--908
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'In the past, people with bad credit have had difficulty getting car loans. And even if they were able to get a car loan in %REGION%, it was often only for a lower quality vehicle. DriveTime focuses on finding and financing the right car for you. ', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'car-loans' AND dynamicItem = 'metadescription'; 
--296
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Start your used car shopping here. DriveTime offers a 5-day return policy & 30 day / 1500 mile limited warranty with every purchase.', 
 WHERE dynamickey = 'article' AND dynamicForm = 'used-car' AND dynamicItem = 'metadescription'; 
--679
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Start your search for a cheap car here! See pictures, prices, and features of  trucks in %REGION% on DriveTime.com! ', 
 WHERE dynamickey = 'vft-article-seo' AND dynamicForm = 'cheap-truck' AND dynamicItem = 'metadescription'; 
--864
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Looking for cheap used cars in %REGION%?  Start your Used Car Search at DriveTime.', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'cheap-car' AND dynamicItem = 'metatitle'; 
--874
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Used Auto Sales at DriveTime %REGION% -  Find Used Autos | DriveTime %REGION%', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'used-auto-sales' AND dynamicItem = 'metatitle'; 
--188
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p>View our selection of %MAKE% %MODEL%s for sale in %REGION%.  At DriveTime, we not only offer you the %MAKE% %MODEL% that you are looking for, but a better and more simple car buying experience. Our %REGION% DriveTime sales advisors are educated professionals there to assist you in the buying process and find the right car for you, regardless of your credit situation. </p><p>All of our %REGION% %MAKE% %MODEL%s pass a multi-point inspection* so the used %MAKE% %MODEL% you find on our used car lot has passed our standards before it ever reaches the lot. Don&#39;t fall victim to pushy salespeople who are just hunting for a commission check at other %MAKE% %MODEL% dealerships.</p><p>When looking for %MAKE% %MODEL%s in %REGION%, your first stop should be DriveTime.  Schedule a visit or stop by a dealership today!</p><br>*DriveTime is not able to complete recall repairs, so vehicles may be subject to open recalls.ÿ You can check whether any vehicle is subject to an unrepaired recall at <a href="http://www.safercar.gov/" target="_blank">www.safercar.gov</a></p>', 
 WHERE dynamickey = 'seo-section' AND dynamicForm = 'region-results-model' AND dynamicItem = 'content'; 
--184
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p>Finding a used car, truck, SUV or van for sale in %REGION% has never been so simple. With over %VEHICLECOUNT% used vehicles in stock for you to choose from, we are confident that we can help you find your next used vehicle. Used car shopping in %REGION% can be difficult with all the options and bogus sales schemes around today, but finding a used car for sale in %REGION% at DriveTime will streamline your experience. </p><p>Our %REGION% Used Car Dealerships offer a used car-buying experience that is second to none. No more pushy salesmen, bait and switch or snake oil programs here. Beware of Buy Here Pay Here dealerships in %REGION%, which advertise a lot and actually deliver a little. Every DriveTime used car goes through a multi-point inspection* before it ever arrives on the lot.</p><p> All these vans and SUVs come with our multi-point inspection* and several post-sale packages to help give you peace of mind. Need a family vehicle in %REGION%? Check out our used SUVs and used Vans available.</p><br>*DriveTime is not able to complete recall repairs, so vehicles may be subject to open recalls.ÿ You can check whether any vehicle is subject to an unrepaired recall at <a href="http://www.safercar.gov/" target="_blank">www.safercar.gov</a></p>', 
 WHERE dynamickey = 'seo-section' AND dynamicForm = 'region-results' AND dynamicItem = 'content'; 
--401
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Not Used- Correctly', 
 WHERE dynamickey = 'car-search' AND dynamicForm = 'index-region-make' AND dynamicItem = 'content'; 
--301
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p>Buying used cars in %REGION% is a simple at DriveTime. Visit our %REGION% DriveTime dealerships today with %VEHICLECOUNT% cars to choose from, many which will fit your needs and desires. </p> <p>Beware of Buy Here Pay Here car lots in %REGION%, who do not offer the same used car dealership experience, the large vehicle selection, or the simple auto loan approvals that DriveTime %REGION% has to offer. DriveTime %REGION% offers auto loans to people of all credit types, including people with bad credit or no credit. Since 2002, we have perfected finding the right used car with suitable auto financing options in a no-hassle, no-pressure used car dealership experience. </p> <p>Our used cars for sale at our %REGION% dealerships arrive at our car lots after they have been through our multi-point inspection* process. All of our used cars in %REGION% and information on our dealership financing options are available to you online, ensuring your purchase from DriveTime %REGION% is the right move for you. </p> <p>Don&#39;t make DriveTime your last resort while looking for used car dealerships in %REGION%, check out our large selection of used cars, trucks, SUVs and vans with great auto financing options today!</p> <br>*DriveTime is not able to complete recall repairs, so vehicles may be subject to open recalls.ÿ You can check whether any vehicle is subject to an unrepaired recall at <a href="http://www.safercar.gov/" target="_blank">www.safercar.gov</a></p>', 
 WHERE dynamickey = 'seo-section' AND dynamicForm = 'dealer-list-regional' AND dynamicItem = 'content'; 
--306
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Don&#39;t fall for other %REGION% used car dealer tricks.  DriveTime %REGION% offers a wide selection cars and great deals.', 
 WHERE dynamickey = 'seo-section' AND dynamicForm = 'dealer-list-regional' AND dynamicItem = 'seo_h2'; 
--186
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p>Find used cars, trucks, vans and SUVs at our %DEALERNAME% DriveTime used car dealership.  With over %VEHICLECOUNT% used cars to choose from and simple financing options we are sure that we can get you a great deal, no matter your credit situation.</p><p>Our %DEALERNAME% experience is better than the typical experience that you would receive at other %REGION% used car dealerships.  Our sales advisors are friendly and focused on getting you the right car for  your situation and our application process for financing is simple.  Along with these conveniences our %DEALERNAME% location has a huge selection of used cars that are inspected* before they are delivered to our lot.</p><p>Call our %DEALERNAME% dealership today at %DEALERPHONE% to schedule a visit or visit us at:</p><p>%DEALERNAME%<br/>%DEALERADDRESS%<br/>%DEALERCITY%, %ST% %DEALERZIP%</p><br>*DriveTime is not able to complete recall repairs, so vehicles may be subject to open recalls.ÿ You can check whether any vehicle is subject to an unrepaired recall at <a href="http://www.safercar.gov/" target="_blank">www.safercar.gov</a></p>', 
 WHERE dynamickey = 'seo-section' AND dynamicForm = 'region-results-deal' AND dynamicItem = 'content'; 
--187
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p>Looking for used %MAKE%s in %REGION%?  Experience the DriveTime difference, where shopping for %MAKE% cars, trucks, vans & SUVs is simple and hassle-free.  Don&#39;t wait around at used %MAKE% dealerships in %REGION% while they play games with you to get the best deal for themselves.  Our sales staff is friendly and focused on getting you into the right used %MAKE% for you, leaving you with a low-pressure sales experience that you dictate </p><p> Our %MAKE% vehicle selection in %REGION% could be just what you&#39;re looking forl, whether you are struggling to get financing or not.  We carry a selection of used %MAKE% vehicles, which are all inspected* before they get to our %REGION% dealerships, giving you peace of mind when buying your used                                                                                                                                                             %MAKE% in %REGION%. </p><p>Come into a %REGION% DriveTime location today and test drive a %MAKE% for sale today.  You&#39;re sure to find a used car buying experience like no other!</p><br>*DriveTime is not able to complete recall repairs, so vehicles may be subject to open recalls.ÿ You can check whether any vehicle is subject to an unrepaired recall at <a href="http://www.safercar.gov/" target="_blank">www.safercar.gov</a></p>', 
 WHERE dynamickey = 'seo-section' AND dynamicForm = 'region-results-make' AND dynamicItem = 'content'; 
--230
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p>Buying used cars is a simple and better experience at DriveTime.  Visit any of our DriveTime dealerships today, each having a wide selection of cars to choose from and many of which will fit your needs and desires.  </p>  <p>Beware of Buy Here Pay Here car lots, who do not offer the same used car dealership experience, the large vehicle selection, or the simple auto loan approvals that DriveTime has to offer.  DriveTime offers auto loans to people of all credit types, including people with bad credit or no credit.  Since 2002, we have worked towards perfecting the used car buying experience by providing a wide vehicle selection, upfront pricing and a no-hassle, no-pressure used car dealership experience.  </p>  <p>Our used cars for sale arrive at our car lots after they have been cleaned and inspected* and come with w 30 Day / 1500 mile limited warranty.  </p>  <p>Don&#39;t make DriveTime your last resort while looking for used car dealerships. Shop online or in store at a dealership location near you. We have a large selection of used cars, trucks, SUVs and vans with great auto financing options for your credit situation!</p>  <br>*DriveTime is not able to complete recall repairs, so vehicles may be subject to open recalls.ÿ You can check whether any vehicle is subject to an unrepaired recall at <a href="http://www.safercar.gov/" target="_blank">www.safercar.gov</a></p>', 
 WHERE dynamickey = 'seo-section' AND dynamicForm = 'dealer-list' AND dynamicItem = 'content'; 
--170
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p>Welcome to DriveTime [REGION]! No matter where you&#39;re at in the process of used car shopping, you&#39;ve found the right place! From our online shopping experience to a visit to one of our [DEALERS] used car dealerships nationwide, you&#39;ll encounter a great used car buying experience in [REGION].</p><p>Used car shopping and visiting dealerships can be a hassle. You have salesmen trying to push you to make decisions that day, draw out the time you are in the dealership, and offer cars that are cleaned but rarely inspected. Visits to our used car dealerships are much different. Our prices are no-haggle, so the price you see is the price you pay, no games. At the end of the day, we provide a simple process that is dictated by your needs and focused on providing fair financing options for a used car. Plus, our used cars come with a 30-day, 1,500 mile limited warranty and a 5-day return policy.</p><p>No matter your credit situation, good or poor, DriveTime [REGION] has auto financing options to make used car ownership as simple as possible. Don&#39;t fall for other dealerships that promise a huge inventory of used cars -- your car selection may be limited by your credit score. Most used car dealerships over promise and under deliver when it comes to getting a great deal and selection.</p><p>Buying a used car in [REGION] is an important decision, and we at DriveTime understand that. Give us a chance to show you how different DriveTime is and how we can get you into a used car, truck, SUV or van that you need today. Take two minutes and start the auto financing approval process above, or schedule a visit online today! </p>', 
 WHERE dynamickey = 'microsites' AND dynamicForm = 'article' AND dynamicItem = 'content'; 
--171
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = ' Looking for Used Cars in [REGION]? Shop the dealership with financing options for all credit types! Buy Here Pay Here Car Dealers cannot compete with our car buying experience', 
 WHERE dynamickey = 'microsites' AND dynamicForm = 'article' AND dynamicItem = 'description'; 
--174
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = ' Find a Used Vehicle with Car Loan Options at DriveTime', 
 WHERE dynamickey = 'microsites' AND dynamicForm = 'article' AND dynamicItem = 'seo_h2'; 
--498
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Not Used - Intentionally', 
 WHERE dynamickey = 'home-seo' AND dynamicForm = 'used-cars' AND dynamicItem = 'content'; 
--499
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Not Used - Intentionally', 
 WHERE dynamickey = 'home-seo' AND dynamicForm = 'buy-here-pay-here' AND dynamicItem = 'content'; 
--500
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Not Used- Intentionally', 
 WHERE dynamickey = 'home-seo' AND dynamicForm = 'bad-credit-auto-financing' AND dynamicItem = 'content'; 
--501
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Not Used - Intentionally', 
 WHERE dynamickey = 'home-seo' AND dynamicForm = 'no-credit-auto-financing' AND dynamicItem = 'content'; 
--502
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Not Used - Intentionally', 
 WHERE dynamickey = 'home-seo' AND dynamicForm = 'bad-credit-car-loan' AND dynamicItem = 'content'; 
--503
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Not Used - Intentionally', 
 WHERE dynamickey = 'home-seo' AND dynamicForm = 'no-credit-car-loan' AND dynamicItem = 'content'; 
--504
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Not Used - Intentionally', 
 WHERE dynamickey = 'home-seo' AND dynamicForm = 'car-sales' AND dynamicItem = 'content'; 
--505
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Not Used - Intentionally', 
 WHERE dynamickey = 'home-seo' AND dynamicForm = 'used-vehicles' AND dynamicItem = 'content'; 
--506
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Not Used - Intentionally', 
 WHERE dynamickey = 'home-seo' AND dynamicForm = 'used-car-dealers' AND dynamicItem = 'content'; 
--547
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Not Used - Intentionally', 
 WHERE dynamickey = 'home-seo' AND dynamicForm = 'used-vehicles' AND dynamicItem = 'seo_h2'; 
--929
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Shop for  Used Vans at DriveTime %REGION% | DriveTime', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'used-van' AND dynamicItem = 'metatitle'; 
--852
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '%REGION% Used Cars for Sale at DriveTime', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'used-car' AND dynamicItem = 'seo_h1'; 
--916
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'Find Used Trucks at DriveTime %REGION%', 
 WHERE dynamickey = 'mobile-article-region-article' AND dynamicForm = 'used-truck' AND dynamicItem = 'seo_h1'; 
--189
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = '<p>Choosing the right vehicle to purchase can be a real hassle and we truly understand that at DriveTime in %REGION%.  That&#39;s why we offer a lot more than other dealerships in %REGION% do.  Our sales experience is not pushy, our financial approval process is easy, and we offer a large selection of used cars, trucks, and SUVs. These are only a few of the benefits of shopping at DriveTime %REGION%.</p><p>With %VEHICLECOUNT% used cars on the lot in %REGION% , we are sure that we will have a used car, truck, van or SUV to fit your needs.  All of our vehicles must pass a Multi-point inspection* before they hit our %REGION% dealership lots to give you peace of mind on your purchase.</p><p>Avoid the poor experience you&#39;ll receive at Buy Here Pay Here car lots in %REGION% and shop for your used vehicle at a DriveTime location near you today.</p><br>*DriveTime is not able to complete recall repairs, so vehicles may be subject to open recalls.ÿ You can check whether any vehicle is subject to an unrepaired recall at <a href="http://www.safercar.gov/" target="_blank">www.safercar.gov</a></p>', 
 WHERE dynamickey = 'seo-section' AND dynamicForm = 'region-results-noseo' AND dynamicItem = 'content'; 
--757
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'DriveTime offers a 30 day / 1500 mile limited warranty to all DriveTime vehicle purchases. Schedule a test drive and ask about our warranties today!', 
 WHERE dynamickey = 'difference-seo' AND dynamicForm = 'drivecare' AND dynamicItem = 'metadescription'; 
--758
SELECT [dbo].[tblDynamicPage] SET RowUpdatedDateTime = GetDate(),  dynamicValue = 'DriveCare Protection Plan, 30 day / DriveTime 1500 mile Limited Warranty', 
 WHERE dynamickey = 'difference-seo' AND dynamicForm = 'drivecare' AND dynamicItem = 'metakeywords'; 
